<?php

/**
 * Adds the OSM
 */
function osmfau_leaflet_map_info() {
    return array(
      'OSM FAU' => array(
        'label' => 'OSM FAU Server',
        'description' => t('OpenStreetMap RRZE Server Map. '),
        'settings' => array(
          'dragging' => TRUE,
          'touchZoom' => TRUE,
          'scrollWheelZoom' => TRUE,
          'doubleClickZoom' => TRUE,
          'zoomControl' => TRUE,
          'attributionControl' => TRUE,
          'trackResize' => TRUE,
          'fadeAnimation' => TRUE,
          'zoomAnimation' => TRUE,
          'closePopupOnClick' => TRUE,
          'layerControl' => TRUE,
           'minZoom' => 0,
           'maxZoom' => 19,
        ),
        'layers' => array(
          'earth' => array(
            'urlTemplate' => '//osm.rrze.fau.de/osmdehd/{z}/{x}/{y}.png',
            'options' => array(
              'attribution' => 'OSM Mapnik',
              // The switchZoom controls require multiple layers, referencing one
              // another as "switchLayer".
              'switchZoomBelow' => 15,
              'switchLayer' => 'satellite',
            ),
          ),
        ),
      ),
    );
  }